sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B
  - cd MRS2020_T10
dist: trusty

deploy:
  provider: heroku
  api_key: c4db25e0-39fb-4775-8582-d6780d5f52dd
  app: app-klinikatim10